<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Promise</title>
    <style>
        *{
            margin-left: 30px;
        }
        p{
            margin-left: 40px;
        }
    </style>
</head>
<body>
<div>
    <ul>
        <li>
            Promise构造函数接受一个函数作为参数，该函数的两个参数分别是resolve和reject.
        </li>
        <li>
            resolve的作用是 将Promise对象的状态从“未完成”变为“成功”（即从pending变为resolved），在异步操作成功时调用，并将异步操作的结果，作为参数传递出去。
        </li>
        <li>
            p2的resolve参数可以是Promise对象p1
        </li>
        <li style="color: red">
            注意，这时p1的状态就会传递给p2，也就是说，p1的状态决定了p2的状态。如果p1的状态是pending，那么p2的回调函数就会等待p1的状态改变；如果p1的状态已经是resolved或者rejected，那么p2的回调函数将会立刻执行。
        </li>
        <li>
            reject的作用是 将Promise对象的状态从“未完成”变为“失败”（即从pending变为rejected），在异步操作失败时调用，并将异步操作报出的错误，作为参数传递出去。
        </li>
    </ul>
    <div>
        <h3>Promise.prototype.then()</h3>
        <p>
            then方法返回的是一个新的Promise实例（注意，不是原来那个Promise实例）。因此可以采用链式写法，即then方法后面再调用另一个then方法。
        </p>
        <h3>Promise.prototype.catch()</h3>
        <p>
            catch用于指定发生错误时的回调函数。
        </p>
        <p>then()方法指定的回调函数，如果运行中抛出错误，也会被catch()方法捕获。</p>
        <p>
            Promise 对象的错误具有“冒泡”性质，会一直向后传递，直到被捕获为止。也就是说，错误总是会被下一个catch语句捕获
        </p>
        <p>
            Promise 内部的错误不会影响到 Promise 外部的代码，通俗的说法就是“Promise 会吃掉错误”。
        </p>
        <h3>Promise.all</h3>
        <p>
            const p = Promise.all([p1,p2]);
            p.then(res=>{res是一个数组});
            Promise.all参数是数组，必须具有Iterator接口

        </p>
        <h3>
            Promise.resolve()
        </h3>
        <p>
            将现有的对象或者值转为Promise对象。
        </p>
        <h3>
            Promise.reject(reason)
        </h3>
        <p>
            返回一个新的Promise实例，该实例的状态是rejected。
        </p>
    </div>
</div>
</body>
<script>
    {
        //ajax函数封装
        function ajax(method, url, data) {
            let request = new XMLHttpRequest();
            return new Promise(function (resolve, reject) {
                request.onreadystatechange = function () {
                    if(request.readyState === 4){
                        if(request.status === 200){
                            resolve(request.responseText);
                        }else{
                            reject(request.status);
                        }
                    }
                };
                request.open(method, url);
                // request.setRequestHeader('Content-type', 'application/json');
                request.setRequestHeader('Content-type', 'application/x-www-form-urlencoded');
                request.send(data);
            })


        }
        let p1 = ajax('post', '/process_post', 'first_name=Xu&last_name=Yuanyuan');
        let p2 = ajax('post', '/process_post', 'first_name=Jin&last_name=Shaopeng');
        let p = Promise.all([p1,p2]);
        p.then(res=>{
            console.log(res);
        })
    }

    {
        function loadImageAsync(url){
            return new Promise(function (resolve, reject) {
                const image = new Image();
                image.onload = function () {
                    resolve(image);
                };
                image.onerror = function () {
                    reject(new Error('Could not load image at '+url));
                }
                image.src = url;
            })
        }
    }

    {
        const getJSON = function (url) {
            const promise = new Promise(function (resolve, reject) {
                const client = new XMLHttpRequest();
                client.open("GET", url);
                client.onreadystatechange = function () {
                    if(this.readyState === 4 && this.status === 200){
                        resolve(this.response);
                    }else{
                        reject(new Error(this.statusText));
                    }
                };
                client.responseType = "json";
                client.setRequestHeader("Accept", "application/json");
                client.send();
            })
        }
    }


    {
        const p1 = new Promise(function (resolve, reject) {
            // setTimeout(()=>reject(new Error('fail')), 3000)
            setTimeout(()=>{
                console.log('done')
            }, 3000)
        })

        const p2 = new Promise(function (resolve, reject) {
            setTimeout(()=>{
                resolve(p1)
            }, 1000);
        })

        p2.then(result => console.log(result))
            .catch(error => console.log(error))
    }


    {
        const someAsyncThing = function () {
            return new Promise(function (resolve, reject) {
                resolve(x+1);
            });
        };
        someAsyncThing().then(function () {
            console.log('everything is great')
        });

        setTimeout(()=>{
            console.log(124)
        }, 0)
    }






</script>
</html>